# usia = int(input("masukan usia anda"))
# if usia == 18 :
#     print("usia anda dewasa")
# else:
#     print("usia anda belum dewasa")

# a = 200
# b = 33
# if (a > b):
#     print("sudah masuk")
#     print("a lebih besar darin pada b")
# else:
#       print("b lebih besar dri pada a")



beratbadan = int(input("silahkan masukkan berat badan"))
if(beratbadan > 100):
    print("berat badan tidak ideal")
else:
    print("berat badan ideal")