# Inisialisasi variabel
nama_toko = "Toko Buku Python"
buku = "Python for Beginners"
harga = 49000
jumlah_beli = 3

# Hitung total harga
total_harga = harga * jumlah_beli

# Cetak struk pembelian
print("===============================")
print("Struk Pembelian Buku - " + nama_toko)
print("===============================")
print("Nama Buku: " + buku)
print("Jumlah Beli: " + str(jumlah_beli))
print("Harga Satuan: Rp. " + str(harga))
print("Total Harga: Rp. " + str(total_harga))
print("===============================")
print("Terima kasih telah berbelanja di " + nama_toko + "!")